# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import comms_pb2 as comms__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in comms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskQueueServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchNextTask = channel.unary_unary(
                '/northstar.TaskQueueService/FetchNextTask',
                request_serializer=comms__pb2.RunnerIdentity.SerializeToString,
                response_deserializer=comms__pb2.NSRTaskResponse.FromString,
                _registered_method=True)
        self.SendHeartBeat = channel.unary_unary(
                '/northstar.TaskQueueService/SendHeartBeat',
                request_serializer=comms__pb2.NSRHeartBeat.SerializeToString,
                response_deserializer=comms__pb2.NSRTaskResponse.FromString,
                _registered_method=True)


class TaskQueueServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchNextTask(self, request, context):
        """nsrunner pulls tasks via this outbound endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendHeartBeat(self, request, context):
        """nsrunner pushes its 15-second system metrics here
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskQueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FetchNextTask': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchNextTask,
                    request_deserializer=comms__pb2.RunnerIdentity.FromString,
                    response_serializer=comms__pb2.NSRTaskResponse.SerializeToString,
            ),
            'SendHeartBeat': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHeartBeat,
                    request_deserializer=comms__pb2.NSRHeartBeat.FromString,
                    response_serializer=comms__pb2.NSRTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'northstar.TaskQueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('northstar.TaskQueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskQueueService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchNextTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/northstar.TaskQueueService/FetchNextTask',
            comms__pb2.RunnerIdentity.SerializeToString,
            comms__pb2.NSRTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendHeartBeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/northstar.TaskQueueService/SendHeartBeat',
            comms__pb2.NSRHeartBeat.SerializeToString,
            comms__pb2.NSRTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
