services:

  api:
    build: 
      context: .
      dockerfile: nsapi/nsapi.Dockerfile
    image: ns-api:latest
    container_name: ns-api
    ports:
      - "8000:8000"
    env_file:
      - .env

  provisioner:
    build: 
      context: .
      dockerfile: nsprovisioner/nsprovisioner.Dockerfile
    image: ns-prv:latest
    container_name: ns-prv
    env_file:
      - .env
    depends_on:
      - redis

  runner:
    build: 
      context: .
      dockerfile: nsrunner/nsrunner.Dockerfile
    image: ns-run:latest
    container_name: ns-run
    privileged: true
    volumes:
      - /var/lib/containerd:/var/lib/containerd
      - /run/containerd:/run/containerd
      - /tmp/workspaces:/tmp/workspaces
    environment:
      - RUNNER_ID=runner-123
      - PYTHONPATH=/app

  redis:
    image: redis:7 
    container_name: ns-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  beat:
    build: .
    command: celery -A nsrunner.imgmgr beat --loglevel=info
    container_name: ns-beat
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A shared.worker worker --loglevel=info
    container_name: ns-worker
    privileged: true
    volumes:
      - /run/containerd:/run/containerd
      - /var/lib/containerd:/var/lib/containerd
    depends_on:
      - redis

  storage:
    image: minio/minio
    container_name: ns-storage
    ports:
      - "9000:9000"    # API Port 
      - "9001:9001"    # Console Port (open in browser)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  redis_data: {}
  pgdata:
  minio_data: