# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import coordinator_pb2 as coordinator__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coordinator_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NSControlPlaneStub(object):
    """
    The core control plane service managing global nodes
    Bi-directional stream: Runner continuously streams health/telemetry up,
    and nsprovisioner streams tasks/actions down over the exact same pipe.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EstablishControlChannel = channel.stream_stream(
                '/northstar.NSControlPlane/EstablishControlChannel',
                request_serializer=coordinator__pb2.NSTelemetryHeartBeat.SerializeToString,
                response_deserializer=coordinator__pb2.NSTaskAssignment.FromString,
                _registered_method=True)


class NSControlPlaneServicer(object):
    """
    The core control plane service managing global nodes
    Bi-directional stream: Runner continuously streams health/telemetry up,
    and nsprovisioner streams tasks/actions down over the exact same pipe.
    """

    def EstablishControlChannel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NSControlPlaneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EstablishControlChannel': grpc.stream_stream_rpc_method_handler(
                    servicer.EstablishControlChannel,
                    request_deserializer=coordinator__pb2.NSTelemetryHeartBeat.FromString,
                    response_serializer=coordinator__pb2.NSTaskAssignment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'northstar.NSControlPlane', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('northstar.NSControlPlane', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NSControlPlane(object):
    """
    The core control plane service managing global nodes
    Bi-directional stream: Runner continuously streams health/telemetry up,
    and nsprovisioner streams tasks/actions down over the exact same pipe.
    """

    @staticmethod
    def EstablishControlChannel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/northstar.NSControlPlane/EstablishControlChannel',
            coordinator__pb2.NSTelemetryHeartBeat.SerializeToString,
            coordinator__pb2.NSTaskAssignment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
