# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coordinator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'coordinator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63oordinator.proto\x12\tnorthstar\"\x91\x01\n\x14NSTelemetryHeartBeat\x12\x11\n\trunner_id\x18\x01 \x01(\t\x12\x16\n\x0e\x63urrent_job_id\x18\x02 \x01(\t\x12\x0e\n\x06region\x18\x03 \x01(\t\x12\x11\n\tqueue_len\x18\x04 \x01(\x05\x12\x14\n\x0c\x65ma_velocity\x18\x05 \x01(\x02\x12\x15\n\rbacklog_scope\x18\x06 \x01(\x02\"P\n\x10NSTaskAssignment\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x11\n\trepo_name\x18\x02 \x01(\t\x12\x19\n\x11pre_signed_s3_url\x18\x03 \x01(\t2m\n\x0eNSControlPlane\x12[\n\x17\x45stablishControlChannel\x12\x1f.northstar.NSTelemetryHeartBeat\x1a\x1b.northstar.NSTaskAssignment(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coordinator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NSTELEMETRYHEARTBEAT']._serialized_start=33
  _globals['_NSTELEMETRYHEARTBEAT']._serialized_end=178
  _globals['_NSTASKASSIGNMENT']._serialized_start=180
  _globals['_NSTASKASSIGNMENT']._serialized_end=260
  _globals['_NSCONTROLPLANE']._serialized_start=262
  _globals['_NSCONTROLPLANE']._serialized_end=371
# @@protoc_insertion_point(module_scope)
