// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: comms.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskExec_PushTask_FullMethodName = "/northstar.TaskExec/PushTask"
)

// TaskExecClient is the client API for TaskExec service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// port 50051 | nsprovisioner sends one way task payload to nsrunner
type TaskExecClient interface {
	// Unary RPC: Scheduler pushes a task, runner drops it into the local pipeline queue instantly
	PushTask(ctx context.Context, in *NSRTask, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type taskExecClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskExecClient(cc grpc.ClientConnInterface) TaskExecClient {
	return &taskExecClient{cc}
}

func (c *taskExecClient) PushTask(ctx context.Context, in *NSRTask, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TaskExec_PushTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskExecServer is the server API for TaskExec service.
// All implementations must embed UnimplementedTaskExecServer
// for forward compatibility.
//
// port 50051 | nsprovisioner sends one way task payload to nsrunner
type TaskExecServer interface {
	// Unary RPC: Scheduler pushes a task, runner drops it into the local pipeline queue instantly
	PushTask(context.Context, *NSRTask) (*emptypb.Empty, error)
	mustEmbedUnimplementedTaskExecServer()
}

// UnimplementedTaskExecServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskExecServer struct{}

func (UnimplementedTaskExecServer) PushTask(context.Context, *NSRTask) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method PushTask not implemented")
}
func (UnimplementedTaskExecServer) mustEmbedUnimplementedTaskExecServer() {}
func (UnimplementedTaskExecServer) testEmbeddedByValue()                  {}

// UnsafeTaskExecServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskExecServer will
// result in compilation errors.
type UnsafeTaskExecServer interface {
	mustEmbedUnimplementedTaskExecServer()
}

func RegisterTaskExecServer(s grpc.ServiceRegistrar, srv TaskExecServer) {
	// If the following call panics, it indicates UnimplementedTaskExecServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskExec_ServiceDesc, srv)
}

func _TaskExec_PushTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NSRTask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecServer).PushTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExec_PushTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecServer).PushTask(ctx, req.(*NSRTask))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskExec_ServiceDesc is the grpc.ServiceDesc for TaskExec service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskExec_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "northstar.TaskExec",
	HandlerType: (*TaskExecServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushTask",
			Handler:    _TaskExec_PushTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comms.proto",
}

const (
	Heartbeat_SendHeartbeat_FullMethodName = "/northstar.Heartbeat/SendHeartbeat"
)

// HeartbeatClient is the client API for Heartbeat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// port 50052 | nsrunner sends one way heartbeat paylaods in set interval
type HeartbeatClient interface {
	// Unary RPC: Runner hits this every 15 seconds to stream telemetry spikes
	SendHeartbeat(ctx context.Context, in *NSRHeartBeat, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type heartbeatClient struct {
	cc grpc.ClientConnInterface
}

func NewHeartbeatClient(cc grpc.ClientConnInterface) HeartbeatClient {
	return &heartbeatClient{cc}
}

func (c *heartbeatClient) SendHeartbeat(ctx context.Context, in *NSRHeartBeat, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Heartbeat_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HeartbeatServer is the server API for Heartbeat service.
// All implementations must embed UnimplementedHeartbeatServer
// for forward compatibility.
//
// port 50052 | nsrunner sends one way heartbeat paylaods in set interval
type HeartbeatServer interface {
	// Unary RPC: Runner hits this every 15 seconds to stream telemetry spikes
	SendHeartbeat(context.Context, *NSRHeartBeat) (*emptypb.Empty, error)
	mustEmbedUnimplementedHeartbeatServer()
}

// UnimplementedHeartbeatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHeartbeatServer struct{}

func (UnimplementedHeartbeatServer) SendHeartbeat(context.Context, *NSRHeartBeat) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedHeartbeatServer) mustEmbedUnimplementedHeartbeatServer() {}
func (UnimplementedHeartbeatServer) testEmbeddedByValue()                   {}

// UnsafeHeartbeatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HeartbeatServer will
// result in compilation errors.
type UnsafeHeartbeatServer interface {
	mustEmbedUnimplementedHeartbeatServer()
}

func RegisterHeartbeatServer(s grpc.ServiceRegistrar, srv HeartbeatServer) {
	// If the following call panics, it indicates UnimplementedHeartbeatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Heartbeat_ServiceDesc, srv)
}

func _Heartbeat_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NSRHeartBeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeartbeatServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Heartbeat_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeartbeatServer).SendHeartbeat(ctx, req.(*NSRHeartBeat))
	}
	return interceptor(ctx, in, info, handler)
}

// Heartbeat_ServiceDesc is the grpc.ServiceDesc for Heartbeat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Heartbeat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "northstar.Heartbeat",
	HandlerType: (*HeartbeatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendHeartbeat",
			Handler:    _Heartbeat_SendHeartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comms.proto",
}
