// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: comms.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskQueueService_FetchNextTask_FullMethodName = "/northstar.TaskQueueService/FetchNextTask"
	TaskQueueService_SendHeartBeat_FullMethodName = "/northstar.TaskQueueService/SendHeartBeat"
)

// TaskQueueServiceClient is the client API for TaskQueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskQueueServiceClient interface {
	// nsrunner pulls tasks via this outbound endpoint
	FetchNextTask(ctx context.Context, in *RunnerIdentity, opts ...grpc.CallOption) (*NSRTaskResponse, error)
	// nsrunner pushes its 15-second system metrics here
	SendHeartBeat(ctx context.Context, in *NSRHeartBeat, opts ...grpc.CallOption) (*NSRTaskResponse, error)
}

type taskQueueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskQueueServiceClient(cc grpc.ClientConnInterface) TaskQueueServiceClient {
	return &taskQueueServiceClient{cc}
}

func (c *taskQueueServiceClient) FetchNextTask(ctx context.Context, in *RunnerIdentity, opts ...grpc.CallOption) (*NSRTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NSRTaskResponse)
	err := c.cc.Invoke(ctx, TaskQueueService_FetchNextTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskQueueServiceClient) SendHeartBeat(ctx context.Context, in *NSRHeartBeat, opts ...grpc.CallOption) (*NSRTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NSRTaskResponse)
	err := c.cc.Invoke(ctx, TaskQueueService_SendHeartBeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskQueueServiceServer is the server API for TaskQueueService service.
// All implementations must embed UnimplementedTaskQueueServiceServer
// for forward compatibility.
type TaskQueueServiceServer interface {
	// nsrunner pulls tasks via this outbound endpoint
	FetchNextTask(context.Context, *RunnerIdentity) (*NSRTaskResponse, error)
	// nsrunner pushes its 15-second system metrics here
	SendHeartBeat(context.Context, *NSRHeartBeat) (*NSRTaskResponse, error)
	mustEmbedUnimplementedTaskQueueServiceServer()
}

// UnimplementedTaskQueueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskQueueServiceServer struct{}

func (UnimplementedTaskQueueServiceServer) FetchNextTask(context.Context, *RunnerIdentity) (*NSRTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchNextTask not implemented")
}
func (UnimplementedTaskQueueServiceServer) SendHeartBeat(context.Context, *NSRHeartBeat) (*NSRTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendHeartBeat not implemented")
}
func (UnimplementedTaskQueueServiceServer) mustEmbedUnimplementedTaskQueueServiceServer() {}
func (UnimplementedTaskQueueServiceServer) testEmbeddedByValue()                          {}

// UnsafeTaskQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskQueueServiceServer will
// result in compilation errors.
type UnsafeTaskQueueServiceServer interface {
	mustEmbedUnimplementedTaskQueueServiceServer()
}

func RegisterTaskQueueServiceServer(s grpc.ServiceRegistrar, srv TaskQueueServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskQueueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskQueueService_ServiceDesc, srv)
}

func _TaskQueueService_FetchNextTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunnerIdentity)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskQueueServiceServer).FetchNextTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskQueueService_FetchNextTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskQueueServiceServer).FetchNextTask(ctx, req.(*RunnerIdentity))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskQueueService_SendHeartBeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NSRHeartBeat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskQueueServiceServer).SendHeartBeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskQueueService_SendHeartBeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskQueueServiceServer).SendHeartBeat(ctx, req.(*NSRHeartBeat))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskQueueService_ServiceDesc is the grpc.ServiceDesc for TaskQueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskQueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "northstar.TaskQueueService",
	HandlerType: (*TaskQueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchNextTask",
			Handler:    _TaskQueueService_FetchNextTask_Handler,
		},
		{
			MethodName: "SendHeartBeat",
			Handler:    _TaskQueueService_SendHeartBeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comms.proto",
}
