// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: comms.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunnerIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	RunnerId      string                 `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	RunnerIp      string                 `protobuf:"bytes,3,opt,name=runner_ip,json=runnerIp,proto3" json:"runner_ip,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerIdentity) Reset() {
	*x = RunnerIdentity{}
	mi := &file_comms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerIdentity) ProtoMessage() {}

func (x *RunnerIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerIdentity.ProtoReflect.Descriptor instead.
func (*RunnerIdentity) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{0}
}

func (x *RunnerIdentity) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *RunnerIdentity) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *RunnerIdentity) GetRunnerIp() string {
	if x != nil {
		return x.RunnerIp
	}
	return ""
}

func (x *RunnerIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type NSRTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasTask       bool                   `protobuf:"varint,1,opt,name=has_task,json=hasTask,proto3" json:"has_task,omitempty"`
	Task          *NSRTask               `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	HasDeploy     bool                   `protobuf:"varint,3,opt,name=has_deploy,json=hasDeploy,proto3" json:"has_deploy,omitempty"`
	Deploy        *NSRDeployInstruction  `protobuf:"bytes,4,opt,name=deploy,proto3" json:"deploy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NSRTaskResponse) Reset() {
	*x = NSRTaskResponse{}
	mi := &file_comms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NSRTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NSRTaskResponse) ProtoMessage() {}

func (x *NSRTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NSRTaskResponse.ProtoReflect.Descriptor instead.
func (*NSRTaskResponse) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{1}
}

func (x *NSRTaskResponse) GetHasTask() bool {
	if x != nil {
		return x.HasTask
	}
	return false
}

func (x *NSRTaskResponse) GetTask() *NSRTask {
	if x != nil {
		return x.Task
	}
	return nil
}

func (x *NSRTaskResponse) GetHasDeploy() bool {
	if x != nil {
		return x.HasDeploy
	}
	return false
}

func (x *NSRTaskResponse) GetDeploy() *NSRDeployInstruction {
	if x != nil {
		return x.Deploy
	}
	return nil
}

type NSRTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	S3Url         string                 `protobuf:"bytes,4,opt,name=s3url,proto3" json:"s3url,omitempty"`
	TimeoutSec    uint32                 `protobuf:"varint,5,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	MemoryLimitMb uint64                 `protobuf:"varint,6,opt,name=memory_limit_mb,json=memoryLimitMb,proto3" json:"memory_limit_mb,omitempty"`
	MaxStdoutKb   uint64                 `protobuf:"varint,7,opt,name=max_stdout_kb,json=maxStdoutKb,proto3" json:"max_stdout_kb,omitempty"`
	CpuShares     uint64                 `protobuf:"varint,8,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`
	DisktLimits   uint64                 `protobuf:"varint,9,opt,name=diskt_limits,json=disktLimits,proto3" json:"diskt_limits,omitempty"`
	LintRuntime   string                 `protobuf:"bytes,10,opt,name=lint_runtime,json=lintRuntime,proto3" json:"lint_runtime,omitempty"`
	LintCommand   string                 `protobuf:"bytes,11,opt,name=lint_command,json=lintCommand,proto3" json:"lint_command,omitempty"`
	LintEnv       map[string]string      `protobuf:"bytes,12,rep,name=lint_env,json=lintEnv,proto3" json:"lint_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BuildRuntime  string                 `protobuf:"bytes,13,opt,name=build_runtime,json=buildRuntime,proto3" json:"build_runtime,omitempty"`
	BuildCommand  string                 `protobuf:"bytes,14,opt,name=build_command,json=buildCommand,proto3" json:"build_command,omitempty"`
	BuildEnv      map[string]string      `protobuf:"bytes,15,rep,name=build_env,json=buildEnv,proto3" json:"build_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TestRuntime   string                 `protobuf:"bytes,16,opt,name=test_runtime,json=testRuntime,proto3" json:"test_runtime,omitempty"`
	TestCommand   string                 `protobuf:"bytes,17,opt,name=test_command,json=testCommand,proto3" json:"test_command,omitempty"`
	TestEnv       map[string]string      `protobuf:"bytes,18,rep,name=test_env,json=testEnv,proto3" json:"test_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NSRTask) Reset() {
	*x = NSRTask{}
	mi := &file_comms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NSRTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NSRTask) ProtoMessage() {}

func (x *NSRTask) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NSRTask.ProtoReflect.Descriptor instead.
func (*NSRTask) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{2}
}

func (x *NSRTask) GetS3Url() string {
	if x != nil {
		return x.S3Url
	}
	return ""
}

func (x *NSRTask) GetTimeoutSec() uint32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *NSRTask) GetMemoryLimitMb() uint64 {
	if x != nil {
		return x.MemoryLimitMb
	}
	return 0
}

func (x *NSRTask) GetMaxStdoutKb() uint64 {
	if x != nil {
		return x.MaxStdoutKb
	}
	return 0
}

func (x *NSRTask) GetCpuShares() uint64 {
	if x != nil {
		return x.CpuShares
	}
	return 0
}

func (x *NSRTask) GetDisktLimits() uint64 {
	if x != nil {
		return x.DisktLimits
	}
	return 0
}

func (x *NSRTask) GetLintRuntime() string {
	if x != nil {
		return x.LintRuntime
	}
	return ""
}

func (x *NSRTask) GetLintCommand() string {
	if x != nil {
		return x.LintCommand
	}
	return ""
}

func (x *NSRTask) GetLintEnv() map[string]string {
	if x != nil {
		return x.LintEnv
	}
	return nil
}

func (x *NSRTask) GetBuildRuntime() string {
	if x != nil {
		return x.BuildRuntime
	}
	return ""
}

func (x *NSRTask) GetBuildCommand() string {
	if x != nil {
		return x.BuildCommand
	}
	return ""
}

func (x *NSRTask) GetBuildEnv() map[string]string {
	if x != nil {
		return x.BuildEnv
	}
	return nil
}

func (x *NSRTask) GetTestRuntime() string {
	if x != nil {
		return x.TestRuntime
	}
	return ""
}

func (x *NSRTask) GetTestCommand() string {
	if x != nil {
		return x.TestCommand
	}
	return ""
}

func (x *NSRTask) GetTestEnv() map[string]string {
	if x != nil {
		return x.TestEnv
	}
	return nil
}

type NSRDeployInstruction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeployRuntime string                 `protobuf:"bytes,1,opt,name=deploy_runtime,json=deployRuntime,proto3" json:"deploy_runtime,omitempty"`
	DeployEnv     map[string]string      `protobuf:"bytes,2,rep,name=deploy_env,json=deployEnv,proto3" json:"deploy_env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Command       string                 `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Steps         []string               `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NSRDeployInstruction) Reset() {
	*x = NSRDeployInstruction{}
	mi := &file_comms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NSRDeployInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NSRDeployInstruction) ProtoMessage() {}

func (x *NSRDeployInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NSRDeployInstruction.ProtoReflect.Descriptor instead.
func (*NSRDeployInstruction) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{3}
}

func (x *NSRDeployInstruction) GetDeployRuntime() string {
	if x != nil {
		return x.DeployRuntime
	}
	return ""
}

func (x *NSRDeployInstruction) GetDeployEnv() map[string]string {
	if x != nil {
		return x.DeployEnv
	}
	return nil
}

func (x *NSRDeployInstruction) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *NSRDeployInstruction) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

type NSRHeartBeat struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// identity
	OwnerId  string `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	RunnerId string `protobuf:"bytes,2,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	RunnerIp string `protobuf:"bytes,3,opt,name=runner_ip,json=runnerIp,proto3" json:"runner_ip,omitempty"`
	Region   string `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	// system
	CpuPercent  float64 `protobuf:"fixed64,5,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent  float64 `protobuf:"fixed64,6,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	DiskPercent float64 `protobuf:"fixed64,7,opt,name=disk_percent,json=diskPercent,proto3" json:"disk_percent,omitempty"`
	// metadata
	HeartbeatTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=heartbeat_time,json=heartbeatTime,proto3" json:"heartbeat_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NSRHeartBeat) Reset() {
	*x = NSRHeartBeat{}
	mi := &file_comms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NSRHeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NSRHeartBeat) ProtoMessage() {}

func (x *NSRHeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_comms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NSRHeartBeat.ProtoReflect.Descriptor instead.
func (*NSRHeartBeat) Descriptor() ([]byte, []int) {
	return file_comms_proto_rawDescGZIP(), []int{4}
}

func (x *NSRHeartBeat) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *NSRHeartBeat) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *NSRHeartBeat) GetRunnerIp() string {
	if x != nil {
		return x.RunnerIp
	}
	return ""
}

func (x *NSRHeartBeat) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *NSRHeartBeat) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *NSRHeartBeat) GetMemPercent() float64 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *NSRHeartBeat) GetDiskPercent() float64 {
	if x != nil {
		return x.DiskPercent
	}
	return 0
}

func (x *NSRHeartBeat) GetHeartbeatTime() *timestamppb.Timestamp {
	if x != nil {
		return x.HeartbeatTime
	}
	return nil
}

var File_comms_proto protoreflect.FileDescriptor

const file_comms_proto_rawDesc = "" +
	"\n" +
	"\vcomms.proto\x12\tnorthstar\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n" +
	"\x0eRunnerIdentity\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1b\n" +
	"\trunner_id\x18\x02 \x01(\tR\brunnerId\x12\x1b\n" +
	"\trunner_ip\x18\x03 \x01(\tR\brunnerIp\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xac\x01\n" +
	"\x0fNSRTaskResponse\x12\x19\n" +
	"\bhas_task\x18\x01 \x01(\bR\ahasTask\x12&\n" +
	"\x04task\x18\x02 \x01(\v2\x12.northstar.NSRTaskR\x04task\x12\x1d\n" +
	"\n" +
	"has_deploy\x18\x03 \x01(\bR\thasDeploy\x127\n" +
	"\x06deploy\x18\x04 \x01(\v2\x1f.northstar.NSRDeployInstructionR\x06deploy\"\x90\x06\n" +
	"\aNSRTask\x12\x14\n" +
	"\x05s3url\x18\x04 \x01(\tR\x05s3url\x12\x1f\n" +
	"\vtimeout_sec\x18\x05 \x01(\rR\n" +
	"timeoutSec\x12&\n" +
	"\x0fmemory_limit_mb\x18\x06 \x01(\x04R\rmemoryLimitMb\x12\"\n" +
	"\rmax_stdout_kb\x18\a \x01(\x04R\vmaxStdoutKb\x12\x1d\n" +
	"\n" +
	"cpu_shares\x18\b \x01(\x04R\tcpuShares\x12!\n" +
	"\fdiskt_limits\x18\t \x01(\x04R\vdisktLimits\x12!\n" +
	"\flint_runtime\x18\n" +
	" \x01(\tR\vlintRuntime\x12!\n" +
	"\flint_command\x18\v \x01(\tR\vlintCommand\x12:\n" +
	"\blint_env\x18\f \x03(\v2\x1f.northstar.NSRTask.LintEnvEntryR\alintEnv\x12#\n" +
	"\rbuild_runtime\x18\r \x01(\tR\fbuildRuntime\x12#\n" +
	"\rbuild_command\x18\x0e \x01(\tR\fbuildCommand\x12=\n" +
	"\tbuild_env\x18\x0f \x03(\v2 .northstar.NSRTask.BuildEnvEntryR\bbuildEnv\x12!\n" +
	"\ftest_runtime\x18\x10 \x01(\tR\vtestRuntime\x12!\n" +
	"\ftest_command\x18\x11 \x01(\tR\vtestCommand\x12:\n" +
	"\btest_env\x18\x12 \x03(\v2\x1f.northstar.NSRTask.TestEnvEntryR\atestEnv\x1a:\n" +
	"\fLintEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rBuildEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fTestEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x01\n" +
	"\x14NSRDeployInstruction\x12%\n" +
	"\x0edeploy_runtime\x18\x01 \x01(\tR\rdeployRuntime\x12M\n" +
	"\n" +
	"deploy_env\x18\x02 \x03(\v2..northstar.NSRDeployInstruction.DeployEnvEntryR\tdeployEnv\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x12\x14\n" +
	"\x05steps\x18\x04 \x03(\tR\x05steps\x1a<\n" +
	"\x0eDeployEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x02\n" +
	"\fNSRHeartBeat\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1b\n" +
	"\trunner_id\x18\x02 \x01(\tR\brunnerId\x12\x1b\n" +
	"\trunner_ip\x18\x03 \x01(\tR\brunnerIp\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x1f\n" +
	"\vcpu_percent\x18\x05 \x01(\x01R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x06 \x01(\x01R\n" +
	"memPercent\x12!\n" +
	"\fdisk_percent\x18\a \x01(\x01R\vdiskPercent\x12A\n" +
	"\x0eheartbeat_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rheartbeatTime2\xa0\x01\n" +
	"\x10TaskQueueService\x12F\n" +
	"\rFetchNextTask\x12\x19.northstar.RunnerIdentity\x1a\x1a.northstar.NSRTaskResponse\x12D\n" +
	"\rSendHeartBeat\x12\x17.northstar.NSRHeartBeat\x1a\x1a.northstar.NSRTaskResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_comms_proto_rawDescOnce sync.Once
	file_comms_proto_rawDescData []byte
)

func file_comms_proto_rawDescGZIP() []byte {
	file_comms_proto_rawDescOnce.Do(func() {
		file_comms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comms_proto_rawDesc), len(file_comms_proto_rawDesc)))
	})
	return file_comms_proto_rawDescData
}

var file_comms_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_comms_proto_goTypes = []any{
	(*RunnerIdentity)(nil),        // 0: northstar.RunnerIdentity
	(*NSRTaskResponse)(nil),       // 1: northstar.NSRTaskResponse
	(*NSRTask)(nil),               // 2: northstar.NSRTask
	(*NSRDeployInstruction)(nil),  // 3: northstar.NSRDeployInstruction
	(*NSRHeartBeat)(nil),          // 4: northstar.NSRHeartBeat
	nil,                           // 5: northstar.NSRTask.LintEnvEntry
	nil,                           // 6: northstar.NSRTask.BuildEnvEntry
	nil,                           // 7: northstar.NSRTask.TestEnvEntry
	nil,                           // 8: northstar.NSRDeployInstruction.DeployEnvEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_comms_proto_depIdxs = []int32{
	2, // 0: northstar.NSRTaskResponse.task:type_name -> northstar.NSRTask
	3, // 1: northstar.NSRTaskResponse.deploy:type_name -> northstar.NSRDeployInstruction
	5, // 2: northstar.NSRTask.lint_env:type_name -> northstar.NSRTask.LintEnvEntry
	6, // 3: northstar.NSRTask.build_env:type_name -> northstar.NSRTask.BuildEnvEntry
	7, // 4: northstar.NSRTask.test_env:type_name -> northstar.NSRTask.TestEnvEntry
	8, // 5: northstar.NSRDeployInstruction.deploy_env:type_name -> northstar.NSRDeployInstruction.DeployEnvEntry
	9, // 6: northstar.NSRHeartBeat.heartbeat_time:type_name -> google.protobuf.Timestamp
	0, // 7: northstar.TaskQueueService.FetchNextTask:input_type -> northstar.RunnerIdentity
	4, // 8: northstar.TaskQueueService.SendHeartBeat:input_type -> northstar.NSRHeartBeat
	1, // 9: northstar.TaskQueueService.FetchNextTask:output_type -> northstar.NSRTaskResponse
	1, // 10: northstar.TaskQueueService.SendHeartBeat:output_type -> northstar.NSRTaskResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_comms_proto_init() }
func file_comms_proto_init() {
	if File_comms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comms_proto_rawDesc), len(file_comms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comms_proto_goTypes,
		DependencyIndexes: file_comms_proto_depIdxs,
		MessageInfos:      file_comms_proto_msgTypes,
	}.Build()
	File_comms_proto = out.File
	file_comms_proto_goTypes = nil
	file_comms_proto_depIdxs = nil
}
